### ISSUE TITLE
Demonstrate using minimesos 0.5.0

### ISSUE THREAD

**Issue by hantuzun** [ContainerSolutions/mesos-hello-world#3]
The current application uses minimesos 0.4.0. Using minimesos 0.5.0 would demonstrate how to use the new API.

**Comment by sadovnikov** [comment]
Right, good point.
However the same test framework is in minimesos project itself, as system
test

**Comment by frankscholten** [comment]
I will update the README so it says this project has been integrated into [minimesos](https://github.com/ContainerSolutions/minimesos)

**Comment by sadovnikov** [comment]
@frankscholten Should we close this repo then? or reopen this issue?

**Comment by frankscholten** [comment]
Just updated the README. The repo can be left here because it is referred to by a talk from me and @philwinder

**Comment by hantuzun** [comment]
Thanks for pointing that out!
